<?php

function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => "Hello Friend!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
       'title' => 'Farewell Friend!',
       'page callback' => 'say_farewell',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
    return '<p style="font-size:3em;color:red;">Hello my Dr Friedchicken!</p>';
}

function say_farewell() {
    return '<p style="font-size:3em;color:green;">Fare thee well Dr Friedchicken!</p>';
}

function greeting_user_login() {
    $_GET['destination'] = 'welcome';
}

function greeting_user_logout() {
    $_GET['destination'] = 'farewell';
}
